version: '3.8'

services:
  app:
    image: php:8.2-fpm
    container_name: comptogether_app
    working_dir: /var/www/html
    volumes:
      - ./backend:/var/www/html
    networks:
      - comptogether-network

  webserver:
    image: nginx:alpine
    container_name: comptogether_nginx
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www/html
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - comptogether-network

  db:
    image: mysql:8.0
    container_name: comptogether_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: comptogether
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - comptogether-network

networks:
  comptogether-network:
    driver: bridge

volumes:
  dbdata:
